language: rust

cache: cargo

rust:
  - stable

install:
  - rustup component add clippy

script:
  - cargo test --all-features
  - cargo clippy --all-features

notifications:
  email:
    on_success: never


